User.create!(name:  "admin1",
             email: "quanghoan@gmail.com",
             password:              "123456",
             password_confirmation: "123456",
             admin: true)
User.create!(name:  "admin2",
             email: "quanghoan10@gmail.com",
             password:              "123456",
             password_confirmation: "123456",
             admin: true)
User.create!(name:  "user1",
             email: "hoan1@gmail.com",
             password:              "123456",
             password_confirmation: "123456",
             address: "hanoi",
             dob: '22.2.92',
             phone: '0102033')